### PR TITLE
Typo.  Published to npm as offworld-heapdump

### PR DESCRIPTION
**Pull request by hurrymaplelad**

### CODE REVIEW

**Comment by acreeger** [comment]
Right you are! However, it appears I don't have write privileges any more. @MaxwellRebo - can you help?

**Comment by adamn** [comment]
Hi, I'm Adam - new here at Factr.  We're no longer using this project - would you like commit access?

**Comment by hurrymaplelad** [comment]
Woah, three Adams...  I'd love commit access, thanks!

**Comment by adamn** [comment]
@hurrymaplelad Feel free to merge and close this.

**Comment by hurrymaplelad** [comment]
Done! Still needs published for the changes to show up on npmjs.org. Plan to bump the version soon, or want to grant me (npm user `hurrymaplelad`) publish rights?

**Comment by adamn** [comment]
I don't have npm rights - @acreeger can grant you access I believe.

**Comment by acreeger** [comment]
Done!

**Comment by hurrymaplelad** [comment]
Thanks! Published as `v0.1.1`.

**Comment by acreeger** [comment]
Thank you!!

**Pull request merged**
