### PR TITLE
Upgrade to heapdump 0.3.7

### PR DESCRIPTION
**Pull request by blabno**

### CODE REVIEW

**Comment by blabno** [comment]
This should resolve #1

**Comment by adamn** [comment]
We're no longer using this project - would you like commit access?

**Comment by acreeger** [comment]
@adamn - I originally wrote this thing, so you can give me access, and I'll merge this PR.

**Comment by adamn** [comment]
Great!  I've just given you admin access.

**Comment by adamn** [comment]
@acreeger We should get this merged

**Comment by adamn** [comment]
Killing this in favor of #4

**Pull request closed without merging**
